App_Estudiantes/config/routes.rb
Rails.application.routes.draw do
  resources :estudiantes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  root "estudiantes#index"

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

App_Estudiantes/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

App_Estudiantes/app/models/estudiante.rb
class Estudiante < ApplicationRecord
  validates :cel, presence: true
  validates :cel, numericality: { only_integer: true }
end

App_Estudiantes/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

App_Estudiantes/app/controllers/estudiantes_controller.rb
class EstudiantesController < ApplicationController
  before_action :set_estudiante, only: %i[ show edit update destroy ]

  # GET /estudiantes or /estudiantes.json
  def index
    @estudiantes = Estudiante.all
  end

  # GET /estudiantes/1 or /estudiantes/1.json
  def show
  end

  # GET /estudiantes/new
  def new
    @estudiante = Estudiante.new
  end

  # GET /estudiantes/1/edit
  def edit
  end

  # POST /estudiantes or /estudiantes.json
  def create
    @estudiante = Estudiante.new(estudiante_params)

    respond_to do |format|
      if @estudiante.save
        format.html { redirect_to estudiante_url(@estudiante), notice: "Estudiante was successfully created." }
        format.json { render :show, status: :created, location: @estudiante }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @estudiante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estudiantes/1 or /estudiantes/1.json
  def update
    respond_to do |format|
      if @estudiante.update(estudiante_params)
        format.html { redirect_to estudiante_url(@estudiante), notice: "Estudiante was successfully updated." }
        format.json { render :show, status: :ok, location: @estudiante }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @estudiante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estudiantes/1 or /estudiantes/1.json
  def destroy
    @estudiante.destroy!

    respond_to do |format|
      format.html { redirect_to estudiantes_url, notice: "Estudiante was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estudiante
      @estudiante = Estudiante.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def estudiante_params
      params.require(:estudiante).permit(:Nombres, :Apellidos, :Carrera, :Carnet, :fechanac, :cel)
    end
end

App_Estudiantes/app/helpers/application_helper.rb
module ApplicationHelper
end

App_Estudiantes/app/helpers/estudiantes_helper.rb
module EstudiantesHelper
end

App_Estudiantes/app/views/estudiantes/_estudiante.html.erb
<div id="<%= dom_id estudiante %>">
  <p>
    <strong>Nombres:</strong>
    <%= estudiante.Nombres %>
  </p>

  <p>
    <strong>Apellidos:</strong>
    <%= estudiante.Apellidos %>
  </p>

  <p>
    <strong>Carrera:</strong>
    <%= estudiante.Carrera %>
  </p>

  <p>
    <strong>Carnet:</strong>
    <%= estudiante.Carnet %>
  </p>

  <p>
    <strong>Fechanac:</strong>
    <%= estudiante.fechanac %>
  </p>

  <p>
    <strong>Cel:</strong>
    <%= estudiante.cel %>
  </p>

</div>

App_Estudiantes/app/views/estudiantes/_form.html.erb
<%= form_with(model: estudiante) do |form| %>
  <% if estudiante.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(estudiante.errors.count, "error") %> prohibited this estudiante from being saved:</h2>

      <ul>
        <% estudiante.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :Nombres, style: "display: block" %>
    <%= form.text_field :Nombres %>
  </div>

  <div>
    <%= form.label :Apellidos, style: "display: block" %>
    <%= form.text_field :Apellidos %>
  </div>

  <div>
    <%= form.label :Carrera, style: "display: block" %>
    <%= form.text_field :Carrera %>
  </div>

  <div>
    <%= form.label :Carnet, style: "display: block" %>
    <%= form.text_field :Carnet %>
  </div>

  <div>
    <%= form.label :fechanac, style: "display: block" %>
    <%= form.date_field :fechanac %>
  </div>

  <div>
    <%= form.label :cel, style: "display: block" %>
    <%= form.text_field :cel %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

App_Estudiantes/app/views/estudiantes/edit.html.erb
<% content_for :title, "Editing estudiante" %>

<h1>Editing estudiante</h1>

<%= render "form", estudiante: @estudiante %>

<br>

<div>
  <%= link_to "Show this estudiante", @estudiante %> |
  <%= link_to "Back to estudiantes", estudiantes_path %>
</div>

App_Estudiantes/app/views/estudiantes/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Estudiantes" %>

<h1>Estudiantes</h1>

<div id="estudiantes">
  <% @estudiantes.each do |estudiante| %>
    <%= render estudiante %>
    <p>
      <%= link_to "Show this estudiante", estudiante %>
    </p>
  <% end %>
</div>

<%= link_to "New estudiante", new_estudiante_path %>

App_Estudiantes/app/views/estudiantes/new.html.erb
<% content_for :title, "New estudiante" %>

<h1>New estudiante</h1>

<%= render "form", estudiante: @estudiante %>

<br>

<div>
  <%= link_to "Back to estudiantes", estudiantes_path %>
</div>

App_Estudiantes/app/views/estudiantes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @estudiante %>

<div>
  <%= link_to "Edit this estudiante", edit_estudiante_path(@estudiante) %> |
  <%= link_to "Back to estudiantes", estudiantes_path %>

  <%= button_to "Destroy this estudiante", @estudiante, method: :delete %>
</div>

App_Estudiantes/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "App Estudiantes" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>